# Generated by Django 5.2.1 on 2025-05-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_monthly_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
