# Generated by Django 5.2.1 on 2025-05-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='financing_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3')], default=1),
            preserve_default=False,
        ),
    ]
