# Generated by Django 5.2.1 on 2025-05-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cartitem_added_at_cartitem_financing_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='financing_option',
            field=models.IntegerField(),
        ),
    ]
