# Generated by Django 5.2 on 2025-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cartitem_user_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
